### ISSUE TITLE
Overal Editor color

### ISSUE THREAD

**Issue by BransonGitomeh** [Cerealkillerway/materialNote#14]
hey this editor works and looks awesome so far, but is there a way to change the overal color from the black i am getting to maybe blue? i cant seem to figure that out :-) thanks.

**Comment by Cerealkillerway** [comment]
Hi, the best way to achieve that is to edit the sass file (sass/materialNote.scss) and let grunt rebuild the new version for you;
all the colors used to build the editor's UI are defined in the first 25 rows of that file, for example

`$toolbarColor: color("blue", "darken-4") !default;`

is the color of the toolbar, and

`$firstButtonColor: color("blue", "darken-4") !default;`

is the color of the main buttons; here they are defined using [materialize css' colors](http://materializecss.com/color.html); of course you can define them using the standard HTML notation as well...

**Comment by BransonGitomeh** [comment]
Ah thanks a lot, ill give it a shot,
