### ISSUE TITLE
bug in some elements.

### ISSUE THREAD

**Issue by demiantriebl** [Cerealkillerway/materialNote#2]

**Comment by demiantriebl** [comment]
sorry, this problem is the dropdown, all item with a dropdown fails.

**Comment by Cerealkillerway** [comment]
Can you please provide more specific informations about this issue?

**Comment by demiantriebl** [comment]
sorry, i have a problem with a compatibility in this packcage and the package ant the poetic:materialize-scss in the all items with a dropdown, but i can solve that, thanks!, and i need to change the z-indez of the menu in 1, with a 1052 the menu is up of another elements and my diferent sass don't working good.
