### ISSUE TITLE
Cannot paste and drop down menu is not working

### ISSUE THREAD

**Issue by ronrun** [Cerealkillerway/materialNote#34]
Paste: 
Firefox, IE, not working. But Chrome and Edge is normal.

Drop down menu
When clicked, it will reload the page. For example, I type "Hello", then want to change the color to be red, I click the color button, then the page reloads.

**Comment by Cerealkillerway** [comment]
Have you tried using latest materialnote release?

**Comment by ronrun** [comment]
I just tried the latest version 2.0.0, still the same. About the drop down menu, I see the summernote buttons have <button type="button"... >, but materialNote's buttons don't . We know that button's default type is "submit", I think this caused the dropdown menu problem. Why you guys dont have the problem? How did u use it?

**Comment by ronrun** [comment]
My solution for Drop menu is to find the line
`class="waves-effect waves-light btn dropdown`
It's 
`'<button class="waves-effect waves-light btn dropdown ' + (btnClassName ? btnClassName : '') + '"',`
Add type="button"
`'<button type="button" class="waves-effect waves-light btn dropdown ' + (btnClassName ? btnClassName : '') + '"',`

Then drop menu works.

**Comment by ronrun** [comment]
I also see that there was a same issue:

Dropdown menus submit form
#18 opened on 31 Aug 2016 by diegonc

Why the author don't fix this ?

**Comment by Cerealkillerway** [comment]
these should be fixed in latest release
